---

{% raw -%}
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create molecule instance(s)
      lxd_container:
        name: "{{ item.name }}"
        state: started
        source:
          type: image
          mode: pull
          server: "{{ item.server | default('https://images.linuxcontainers.org') }}"
          protocol: simplestreams
          alias: "{{ item.alias | default('ubuntu/bionic/amd64') }}"
        profiles: [ "default" ]
        wait_for_ipv4_addresses: true
        url: "{{ item.url | default('unix:/var/snap/lxd/common/lxd/unix.socket') }}"
        timeout: "{{ item.timeout | default(600) }}"
      with_items: "{{ molecule_yml.platforms }}"
{%- endraw %}
